### ISSUE TITLE
Framerate is read from file header, not analyzed from source

### ISSUE THREAD

**Issue by EposVox** [cirquit/trdrop#21]
I've tried this on a few video clips now, and all it seems to do is read the alleged framerate from the file container header, not actually do any analysis of the framerate of the source footage.
a 60fps encoded video is read as clean 60fps with occasional 59fps bits in the same spots that MPC would show.
A MKV file (which get messed up headers and show 1000 fps in Windows Explorer) jumps up to 996FPS and stays there, despite being of a 60FPS game. 
Etc.
![trdrop_c_2018-04-01_12-57-21](https://user-images.githubusercontent.com/18689681/38175594-fd0516de-35ac-11e8-8c9a-ea8d95ae8de5.png)
![trdrop_c_2018-04-01_12-59-03](https://user-images.githubusercontent.com/18689681/38175595-fd13ca8a-35ac-11e8-9bb1-7bac5c268eac.png)
![trdrop_c_2018-04-01_12-59-50](https://user-images.githubusercontent.com/18689681/38175596-fd2043c8-35ac-11e8-9b85-414bc1c80094.png)

**Comment by cirquit** [comment]
We currently assume a maximal framerate of 60 FPS in a **RAW** container, in other words it shouldn't be encoded at all.

The problem with a broken header is that we use this information to check what a *second* in the recording video actually is, because we count the amount of different frames in a second. If this information is broken, the FPS calculation is triggered wrongly, in your case after ~ `1000` frames. Additionaly, our plotting "library" can't handle values over `60` because the OpenCV font functionality is horrible and we've saved the numbers as glyphs for it to look even remotely *ok*.

The described problem happens [here](https://github.com/cirquit/trdrop/blob/master/trdrop_c/trdrop_c/FPSTextTask.h#L76), where we use the `refreshRate` of the video to trigger the `getFps` function.

I'm very sorry to not have written this down in the Readme. I think a fix would be to get the amount of seconds passed from the current frame information (which was already suggested as a feature in an offline discussion) and trigger the FPSTask after the calculated second.

This would be not dependent on the correct header information, but would be instead dependent on the frame information which should reflect the correct time interval of the recording.

**Comment by EposVox** [comment]
Thanks for the info! Unfortunately uncompressed AVI is not in the realm of possibility for the kinds of captures I am testing (and "RAW" for video game footage is not possible at all - requires a camera that shoots RAW buuuut), but lossless ProRes/DNxHR is enough for this kind of situation. I was just doing basic/lazy testing to see if it would show specific drops.

**Comment by cirquit** [comment]
Please try our new GUI release! We don't have any restrictions on the FPS of the raw container or the calculated FPS.

We still currently depend on the correct header framerate as this reflects directly in the frametime!
