### ISSUE TITLE
Output 720p problem and frame time monitoring

### ISSUE THREAD

**Issue by jcchg** [cirquit/trdrop#24]
First of all, thanks to the devs for the recent update (that let me easily try this program).

<b>Original</b>: <s>I would like to know why this video is speeded up? https://drive.google.com/file/d/14cMZQUqsH7-tWFAT13Amdf2b1ea7Bgk4/view?usp=sharing

Do I have to configure any setting?</s>

<b>Edit</b>: I think it was a perception. Finally, output video doesn't seem speeded up. Sorry if I caused any confusion.

A second question, how can I select 1280x720p output resolution? I tried replacing 1920x1080 with 720p but the program doesn't run.

One last question, is it posible to monitor frametime? 

Thank you.

**Comment by MujoA** [comment]
I'm glad you were able to test the software.

1. I can't say for sure because I don't have the original video, but the difference in speed between the input and output videos is most likely a result of trdrop assuming a different framerate of the input video than it actually is. This could have a number of reasons. Does your input video meet our [Software Limits](https://github.com/cirquit/trdrop#software-limits)? If not, then that might be an issue. If it does, it would be great if you could provide the original video so that we can analyze it more thoroughly. 

2. It should normally be possible to set any resolution in the config. I've tried it though and there seems to be an issue with the video width right now when it is set to less than 1920. This is a bug. We will try to fix this in the next release.
 
3. No, frametime analysis is not supported yet, although we might implement it sometime in the future.

Thanks!

**Comment by cirquit** [comment]
Frametime is implemented in the new GUI release!
