### ISSUE TITLE
trdrop_c app crashes, debug says ucrtbase.dll

### ISSUE THREAD

**Issue by jonstarks** [cirquit/trdrop#25]
trying to get this running, I'm having issues. 

When I run the trdrop_c app, it starts up but eventually crashes before I can do anything. It allows me to run a debug: 

"Unhandled exception at 0x00007FFE0907B70E (ucrtbase.dll) in trdrop_c.exe: Fatal program exit requested."

Any help?

What additional software do I need to install with this

**Comment by cirquit** [comment]
Hmm. Does anybody else have that problem? It looks like some error due to a mismanaged .NET environment  ([SO](https://stackoverflow.com/questions/49065141/unhandled-exception-at-0x74e733ab-ucrtbase-dll-in-openclaw-exe)).

Can you please delete all files and download a fresh copy of the program and run it again? 
Please document every step which you have done up until know so we can try to reproduce it.

**Comment by rafamb91** [comment]
I have problems to run the .exe too. This issue appears when I try to open the program:
https://i.imgur.com/tt4Hq9A.png

**Comment by cirquit** [comment]
@rafamb91 Did you check that the file you're putting in the config exists in the first place? It looks like you're using the default config with my usual test-video `Sample 3 1080p Tearing Watch Dogs 2 PS4.avi`.

**Comment by rafamb91** [comment]
@cirquit sorry, I'm a noob with this. Where I need to put the video for starting? Is there any quick guide for using this program? I'm with this a few days and I would appreciate the help.

**Comment by rafamb91** [comment]
@cirquit Thank you so much, it finally works! Any program recommendation for record avi files? Which program do you use?

**Comment by cirquit** [comment]
I actually don't record at all, I only have recordings of other people. I would recommend to buy an external capture card, because if you simply "screencap" your desktop, there are possibly compression artifacts of software like **Fraps** or **NVidia Shadowplay**. 

This results in wrongly classified tears and possibly frames.

A quick search turned out [this list](https://www.highgroundgaming.com/best-capture-cards/), maybe this can be an orientation point, but feel free to search by yourself.

**Comment by rafamb91** [comment]
@cirquit  I already have an elgato 4K60  to record, I mean a program to record on raw avi format. I just tested trdrop with a recorded video from amarectv with the lagarith codec. The result is trdrop outputs the final video without sound and a bit accelerated. What could cause this? Anyway, you have done a great job with this!

**Comment by rafamb91** [comment]
@cirquit I tried to record with the accompanying software, but it is not allowed to register the variable frame rate. I leave here the recorded video with amarectv:

https://drive.google.com/open?id=1plmICjBPSxvxV6eoowfO8QR1rSSrJu3S

And the result without sound and accelerated:

https://drive.google.com/open?id=1aY_z1UQpz1KPPv-eu68CIbXKcrEkMgu1

I'm also have tried with OBS, but I can't see any variable frame rate option in the latest versions. If someone know about any program that allows this I will test it.

**Comment by cirquit** [comment]
We don't have any more framerate restrictions in the new GUI release, please see if the error is still there!
