### ISSUE TITLE
Use logs (csv) with another video file

### ISSUE THREAD

**Issue by win98and95** [cirquit/trdrop#26]
maybe like this https://youtu.be/fAVxmfNUuRs?t=432

**Comment by cirquit** [comment]
Well, this feature seems nice, but we don't have a GUI interface to support this kind of operation yet. It's possible to allow this feature, but the problem is that these log files may not represent the true values, because the clips have to be synchronized.

This is only possible if the sequence is exactly the same, for each recording, and thus does not represent a real comparison, but mearly a biased summary, like `GTX 980 2G: mean 58/60 fps`.

We're currently thinking about implementing a GUI interface, then a discussion about these features may be possible.
