### ISSUE TITLE
No audio and 2160p not showing in Youtube in .avi output

### ISSUE THREAD

**Issue by jamshiadalam** [cirquit/trdrop#27]
I have Forza Horizon 4 4k video 10 minutes long recorded from XBOX One X, Doing TRDROP framerate testing everything is default in yaml. Input file is .mp4 and output file is .avi and codec is "X264". The output video came good in .avi format but 2 issue i am getting. 
1. No Audio
2. 2160p not showing in Youtube.

I tested again for .mp4 as output but same issue
Please help

Edit: 2160p is Showing in Youtube for .mp4 as output but still no audio.

**Comment by cirquit** [comment]
No audio is currenlty the default behaviour, because we allow multiple video sources and it would be even more difficult to decide what sound track you want to pick in the `.yaml` configuration.

The usual solution is to use any kind of video editing software, cut the track from your respective video file and overlay it over the annotated trdrop video.

We're slowly working towards a GUI in our free time, then it might be possible to choose which sound track you want to keep or mix.

**Comment by jamshiadalam** [comment]
Thanks for your quick reply and i understand your concern about audio. You guys are doing great :)
I have one more question. Is there any way to reduce bitrate? because it seems like its tearing video at the bitrate of 280mbps which is quit high. I want something like 80-100mbps. If its possible. Thanks Again :) Love your work.

**Comment by cirquit** [comment]
I think this is not really possible, because if you reduce the bitrate it with e.g [ffmpeg](https://unix.stackexchange.com/questions/28803/how-can-i-reduce-a-videos-size-with-ffmpeg), there will be compression which will result in a false frame rate calculation, because it **will** modify the pixels.

The only solution is to capture the video in a different bitrate.

**Comment by jamshiadalam** [comment]
Ahh ok, Thats what I want to know Thanks. Thankyou very much. You saved my day. :)
