### ISSUE TITLE
Output log doesn't factor in tearing to FPS values

### ISSUE THREAD

**Issue by ImplyingKinpatsu** [cirquit/trdrop#29]
The output csv doesn't factor in tearing when making the FPS column (trdrop-3.1)

![trdroptearnochange](https://user-images.githubusercontent.com/25698617/57432499-e7fe4f00-71ea-11e9-9f2c-cd001c834934.jpg)

**Comment by cirquit** [comment]
You're totally right. In the plotting module https://github.com/cirquit/trdrop/blob/master/trdrop_c/trdrop_c/PlotTask.h#L213 the framerate is calculated with the tears, but the Logger Task only gets the raw information from https://github.com/cirquit/trdrop/blob/master/trdrop_c/trdrop_c/main.cpp#L114.

This is a bug. Unfortunately, I'm currently working on a rewrite of the whole project in Qt and don't have a a MSVC compiler at hand to fix the issue. 

Actually, I've thought about how to manage tears in general, because the current rule of "if it's more than half the screen, don't count it as a new frame, otherwise do" is not really intuitive and maybe we should simply display the last valid Framerate / or None with some kind of marker (color/font) to show that its unstable. What do you think?

**Comment by ImplyingKinpatsu** [comment]
I don't know much about how tearing works to suggest something, but I think of those two, the way it is right now is better since the framerates can be somewhat hotfixed if it's searching for tears under 50% (where it gets less accurate from what I've seen) in order to be closer to what the numbers actually are, while displaying the last valid/no framerate will need a bit more inferring to read the graph and the logs wouldn't have the intermediate values

**Comment by cirquit** [comment]
Thank you very much for your feedback! I'll think of making it configurable, whatever option one wants to pick. 

I'll make sure to include this bug in the roadmap of the current rewrite so this does not happen again.

**Comment by ImplyingKinpatsu** [comment]
No problem! Thanks for working on this tool

**Comment by cirquit** [comment]
With the new GUI release the CSV log now also incorporates the teared framerate.
