### ISSUE TITLE
Video stops exporting after a few seconds

### ISSUE THREAD

**Issue by illusion98** [cirquit/trdrop#37]
Tested on Windows 10 1903 and first Qt release.
Doesn't matter what codec or video container I used. (lossless AVI also have the same issue)
[Video](https://i.imgur.com/okwEaym.mp4).

**Comment by uncledrax** [comment]
I can report the same problem. I'll try an upload the video I am using to see if that helps.

**Comment by cirquit** [comment]
I currently think that this is related to #35, as it looks visually the same (frame is shown, then it disappears for a short time and then the program crashes). I'm investigating possible solutions right now. 

It looks like a OpenCV out of memory error which happens when the frames are allocated but never freed.

**Comment by illusion98** [comment]
I'll close this for now since it stops exporting once it reaches 1.2~GB Memory usage.
