### ISSUE TITLE
Increase analysis range?

### ISSUE THREAD

**Issue by MadTechGaming** [cirquit/trdrop#40]
Would it be possible to increase the analysis range shown on the plots from the current maximum 180 to something like 300 or 360? I guess it's personal preference but I feel the framerate graph moves abit too fast would be nice to slow it down a little and have abit more info shown at the same time. Actually the frametime plot being smaller is spot on at 180 range, just the framerate one being increased would be beneficial I think.

Thanks for making this tool btw, pure awesome.

**Comment by illusion98** [comment]
While we're on the topic of plot ranges is it possible to set a fixed framerate plot instead of having it varies from (i.e 0-42, 0-34 fps) to something like 0-60 0-40 in a fixed fps plot range.
Letting the user configure the framerate plot range instead of letting the program "generating" the plot range would be a great feature.
<details>
<summary>Examples</summary>

![ ](https://cdn.discordapp.com/attachments/570608724205502464/609785939325222917/unknown.png)
![ ](https://cdn.discordapp.com/attachments/570608724205502464/609786527001608202/unknown.png)
</details>

**Comment by cirquit** [comment]
@MadTechGaming this should be possible. I hoped to tackle this in a short change before the first non-beta release, but I've had some problems with the QML Spinbox where I sets values more or less random? Unfortunately, this change will make it only into the next release (probably mid of September)

@illusion98 This is doable and I'll probably make it configurable to either set the max-range by yourself or letting trdrop calculate it.

**Comment by jezorz** [comment]
Are there any plans still to add this in? :) Software is great otherwise.

**Comment by cirquit** [comment]
I'm currently struggling to find the time to develop trdrop further :( If I find some time over the winter holidays I will try to do a revision of the current features/bugs.

**Comment by cirquit** [comment]
Will be included in the next release
