### ISSUE TITLE
Question: recording 30fps vs 60fps?

### ISSUE THREAD

**Issue by masterant86** [cirquit/trdrop#80]
I’ve looked through all the issues to see if someone already asked but could not find it. Maybe a stupid question but here it comes:

So if you’re analyzing a videogame of which you know it is locked at 30 fps: Would recording at 30 fps be preferable? Or are there any drawbacks to the accuracy of the analysis? Example: game capture at 60 fps with game locked at 30 fps. You get the occasional 31-32-33 fps count. Which I expect (no pixel-diff used)  as it an estimated fps count. If 30 fps is an hard lock on the game I wouldn’t want to show passing above 30 fps on the graph.

Recording with 30 fps would fix the “do not go above 30fps line on the graph”. On the other side of the story I don’t know how the software handles it if you’re outputting 60fps from source and recording at 30 fps and analyzing this recording. Maybe someone could elaborate on this? I know delta rendering and pixel diff can be used in this case but sometimes without the option used it is already in the range of lets say 28-32 fps. If I enable delta rendering and pixel-diff, am I not potentially missing out on frames on the lower count?

For making the graphs look better if recording at 30fps is NOT preferable maybe an option to “stop” counting at 30 for the graph would be an idea? Is the game locked at 30? Yes. Graph will not pass the 30 fps count.

Just trying to get the best possible and feasible results with trdrop and make the look more consistent. And understand how to better use the software.

Thanks.

**Comment by mrDMG89** [comment]
It's a bad idea. The main reason to use 60 fps is 60Hz monitor. It's how your videcard or console puts frames in this 60Hz queue. Not always they put only in even or odd frames.

**Comment by masterant86** [comment]
Ok I think I understand, so if they come in “the wrong” order I might be missing frames resulting in possible lower frame rate and at the same time making the analysis even more inaccurate? In that case the “topping off” at 30fps wouldn’t make sense neither.

Appreciate the reply.

**Comment by cirquit** [comment]
Maybe a small note from my side here - I have a few assumptions that I follow when developing, and you have the hard job of interpreting the results based on those:

1. I do not trust any game rendering setting, nor any game that says it's "locked" to 30/60/magic number of framerate.
2. The only thing I can actually work with are the frames that are supplied. The other parameter in this setup is the recording time, or in other words, the actual recording framerate, on which I base the "real, elapsed time" on.
3. Barring major implementation bugs, I trust the framerate trdrop detects more compared to anything other extremely complicated, closed-source monolithic programs spit out (in this case games, game engines, renderers, etc.)
4. There are always insights generated through `delta-rendering` and `pixel-difference` from which you can infer why the framerate is the way it is. The only thing which is slightly more complicated is the tear-calculations, but I also explained how those work in other issues. I really have to create a bit more documentation about the algorithms...

I just thought about maybe coining a new term for the FPS I'm calculating, as it's not the actual Framerate per second, but a "detectable" FPS, or d-FPS.

This would maybe make a few people mad, but also open up the possibility of speaking about these issues, as games/renderers sell you a certain framerate, but can't actually deliver it consistently (at least visibly)

To come back to your original question, I'd never allow locking the graphs to a fixed range without showing overcapping, as this is not truthful. If you obviously record with a maximum of 30 FPS, then you will never get a higher framerate. But if the original game was not hitting the perfect 30 Hz refresh rate, you will have overlaps, due to the recording software not lining up with the refresh rate of the game software/console GPU. This, in turn, would lead to even less (d-)FPS, compared to your current range 28-32. 

The issue you're describing with not-perfectly aligned frames should be seen in frame-time, first and foremost. Imagine a number is being a unique frame and we have a total time of 1s:

* `0 -> 0 -> 1 -> 1`: this is 2 FPS with a frame-time of 0.5s for each frame
* `0 -> 0 -> 0 -> 1`: this is 2 FPS with a frame-time of 0.75s for frame `0` and 0.25s for frame `1`

As I'm thinking about it, I feel the (Nyquist Theorem)[https://en.wikipedia.org/wiki/Nyquist%E2%80%93Shannon_sampling_theorem] might even apply in this very scenario. To detect consistent 30 FPS, you'd need a recording of 60 FPS.

**Comment by masterant86** [comment]
Appreciate how you take the time to make sure every single question is answered to your best knowledge. I truly do.

So in my mind d-FPS sounds good, not sure why people would get mad over that. It is an amazing piece of software which can be used without any payment and many are using to commercialise it on Youtube. On the other hand, people are people. I think this would even be helpful for new users who are looking at like I did at the beginning. "Why does it pass 30 fps?" Also I think there will always be scenes where even with pixel-difference more than 30 fps will be detected, going higher on pixel-diff will make the FPS go down to a too low (d-)FPS and going lower will give a too high result in (d-)FPS. Most of the times it will handle it, but those (edge) cases exist I guess. Maybe someday it could be automated with like a double pass analysis where the user has to provide the expected FPS. Algorithm could try to have a variable pixel-diff on first run. Of course it would need to be a video of which is visible not dropping frames and so, probably still difficult to judge. Don't know if would be even possible, just thinking (out loud)! 

So from the hours I've spend trying to figure out the pixel-difference settings and how to work them. I might have a suggestion, probably won't fit in your time schedule but; Why not have the community provide you/the community with data? Pixel-difference data. Users can contribute by uploading a CVS and matching it to a game. Just have it exported by default maybe. So you'll know with this pixel-difference highest FPS was XX and lowest was XX for this game. Other users can benefit from not "trial-and-error" on the pixel-difference setting for games running at around 30 fps and those smudgy effects you mentioned. Just a simple portal with a db to your likings. Large data set could come in handy IF someday you decide to commercialise it and make it more "user-friendly". Ow you're trying to analyse this game? This settings seems to work best with most users, autofill pix-diff. I know you already wrote you're not planning on it but Youtube is literately FULL of trdrop-videos, so huge potential if you ask me. Maybe it could bring insights (patterns) you could take in consideration for future updates, again just thinking out load.

Also another suggestion, I saw it on a different issue/question; you should really consider a donate button or patreon. Like I said, many are commercialising and earning from it and would probably be more than happy to contribute to such a great piece of software.  

P.S. your reference to the Nyquist Theorem made me feel really stupid you know? :)
